# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKClient
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'

end
